language: python
python:
  - 2.7
  - 3.3
  - pypy
install:
  - pip3 install pytest
  - pip3 install --process-dependency-links .
script:
  - py.test tests/
notifications:
  email:
    - michael@elsdoerfer.com
branches:
  only:
    - master
